/* 
 *  pts2crg.c
 * ---------------------------------------------------
 *  produces an OpenCRG road from a reference line in PTS format
 * ---------------------------------------------------
 *  first edit: 12.11.2019 by Miguel Leitao
 *  
 * ===================================================
 *  Copyright 2019 DriS Dev Team
 *
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#define MAX_LINE_LEN (180)

int verbose = 0;

typedef double Scalar;

typedef struct {
    int coords;
    int verts;
    int capacity;
    Scalar *data;
} ptsData;

char *trim(char *s) {
    if ( !s ) return s;
    while( *s==' ' ) s++;
    return s;
}

ptsData *newPts(int nCols) {
    ptsData *p = malloc(sizeof(ptsData));
    p->coords = nCols;
    p->verts = 0;
    p->capacity = 0;
    p->data = (Scalar *)NULL;
    return p;
}

void freePts(ptsData *pts) {
    if ( ! pts ) return;
    free(pts->data);
    free(pts);
    return;
}

ptsData *addPtsCapacity(ptsData *pts, int n) {
    pts->capacity += n;
    pts->data = realloc(pts->data, pts->capacity*pts->coords*sizeof(Scalar));
    if ( ! pts->data ) 
        fprintf(stderr,"Error: Could not reallocate\n");
    return pts;
}

ptsData *loadPtsFile(char *fname, int nCols) {
    ptsData *pts = newPts(nCols);
    
    FILE *fin = fopen(fname, "r");
    if ( fin ) {
        char line[MAX_LINE_LEN+1];
        int nlines = 0;
        while( fgets(line, MAX_LINE_LEN, fin) ) {
            nlines++;
            if ( line[0]=='#' ) continue;
            if ( pts->verts>=pts->capacity )
                addPtsCapacity(pts,10);
            Scalar *p = pts->data + pts->verts*pts->coords;
            char *lp = trim(line);
            char *nextp = NULL;
            for( int c=0 ; c<nCols && lp ; c++ ) {
                *p = strtod(lp, &nextp);
                if ( nextp==lp ) 
                    fprintf(stderr,"Error parsing line %d:%d:%s\n", nlines, c, line);
                lp = trim(nextp);
                printf("v=%lf\n", *p);
                p++;
            }
            pts->verts += 1;
        }
    }
    return pts;
}

int saveCrgCtSection(ptsData *pts, FILE *fout) {
    fprintf(fout, "$CT\n");
    fprintf(fout, "CRG file for road surface description\n");
    fprintf(fout, "Generated by pts2crg from PTS data.\n");
    fprintf(fout, "pts2crg is part of the CRGkit utilities suite.\n");
    fprintf(fout, "CRGkit is available from https://github.com/miguelleitao/CRGkit.\n");
    fprintf(fout, "OpenCRG file format description can be found at http://www.opencrg.org\n");
    fprintf(fout, "$!**********************************************************************\n");
    return 0;
    
}

int saveCrgRoadSection(ptsData *pts, FILE *fout) {
    fprintf(fout, "$ROAD_CRG                                          ! crg road parameters\n");
    fprintf(fout, "REFERENCE_LINE_START_U   = 0.0\n");
    fprintf(fout, "REFERENCE_LINE_START_X   = %.4lf\n", pts->data[0]);
    printf("PHI: %lf\n",pts->data[3]);
    fprintf(fout, "REFERENCE_LINE_START_Y   = %.4lf\n", pts->data[1]);
    fprintf(fout, "REFERENCE_LINE_START_PHI = %.4lf\n", pts->data[3]);
    
    fprintf(fout, "REFERENCE_LINE_END_U     = %.4lf\n", 22.0);
    fprintf(fout, "REFERENCE_LINE_END_PHI   = %.4lf\n", 0.);
    fprintf(fout, "REFERENCE_LINE_INCREMENT = 1.0\n");
    fprintf(fout, "LONG_SECTION_V_RIGHT     =-1.50         ! with explicit definition below\n");
    fprintf(fout, "LONG_SECTION_V_LEFT      = 1.50         ! with explicit definition below\n");
    fprintf(fout, "$!**********************************************************************\n");
    return 0;
}

int saveCrgKdSection(ptsData *pts, FILE *fout) {
    fprintf(fout, "$KD_Definition                                   ! data definition block\n");
    fprintf(fout, "#:LRFI                           ! one of the men readable IPLOS formats\n");
    fprintf(fout, "U:reference line u,m,0,1.0     ! virtual channel, only for IPLOS viewing\n");
    //fprintf(fout, "D:reference line banking,m/m             ! lateral banking (cross slope)\n");
    fprintf(fout, "D:reference line phi,rad                                 ! heading angle\n");
    fprintf(fout, "D:long section at v = -1.500,m           ! 1.50m right of reference line\n");
    fprintf(fout, "D:long section at v = -1.250,m           ! 1.25m right of reference line\n");
    fprintf(fout, "D:long section at v = -1.000,m           ! 1.00m right of reference line\n");
    fprintf(fout, "D:long section at v =  0.000,m           !             on reference line\n");
    fprintf(fout, "D:long section at v =  1.000,m           ! 1.00m left  of reference line\n");
    fprintf(fout, "D:long section at v =  1.250,m           ! 1.25m left  of reference line\n");
    fprintf(fout, "D:long section at v =  1.500,m           ! 1.50m left  of reference line\n");
    fprintf(fout, "$!**********************************************************************\n");
    return 0;
}

void printCrgValue(FILE *fout, Scalar v) {
    char format[] = " %.7lf";
    int signal = ( v>=0 ? 0 : 1 );
    fprintf(fout, format+signal, v);
}

int saveCrgDataSection(ptsData *pts, FILE *fout) {
    fprintf(fout, "$$$$$$$$10$$$$$$$$20$$$$$$$$30$$$$$$$$40$$$$$$$$50$$$$$$$$60$$$$$$$$70$$$$$$$$80\n");
    for( int i=1 ; i<pts->verts ; i++ ) {
        double v = pts->data[i*pts->coords+3];      // heading
        printCrgValue(fout, v);
        v = pts->data[i*pts->coords+2];             // Z
        for( int s=0 ; s<7 ; s++ ) 
            printCrgValue(fout, v);
        fprintf(fout,"\n");
    }
    return 0;
}

    
int savePtsCrgFile(ptsData *pts, char *outfilename) {
    // Openoutput file
    FILE *fout = fopen(outfilename, "w");
    if ( ! fout ) {
        fprintf(stderr,"Error opening output file '%s'\n", outfilename);
        return 1;
    }
    saveCrgCtSection(pts, fout);
    saveCrgRoadSection(pts, fout); 
    saveCrgKdSection(pts, fout); 
    saveCrgDataSection(pts, fout);
    fclose(fout);
    return 0;
}


void usage()
{
    fprintf(stderr, "Usage: pts2cgr [options] <filename>\n" );
    fprintf(stderr, "       options: -h            show this info\n" );
    fprintf(stderr, "       options: -v offset     apply transverse offset\n" );
    fprintf(stderr, "       options: -o outfile    save result to outfile\n" );
    fprintf(stderr, "       <filename>  input file\n" );
    exit( -1 );
}

int main( int argc, char** argv ) 
{
    char*  filename = "";
    char  outfilename[80] = "a.crg";
    
    /* --- decode the command line --- */
    if ( argc < 2 )
        usage();
    
    argc--;
    
    while( argc )
    {
        argv++;
        argc--;
        
        if ( *argv[0] != '-' ) continue;
        
        if ( !strcmp( *argv, "-h" ) ) {
            usage();
            continue;
        }
        if ( ! strcmp( *argv, "-v" ) ) {
            argv++;
            argc--;
            if ( argc ) {
                verbose = atof(*argv);
            }
            continue;
        }
        if ( ! strcmp( *argv, "-o" ) ) {
            argv++;
            argc--;
            if ( argc ) {
                strcpy(outfilename,*argv);
            }
            continue;
        }
    }
    
    if ( !argc )    /* last argument is the filename */
    {
        fprintf( stderr, "searching file\n" );
        
        if ( argc < 0 ) {
            fprintf( stderr, "Name of input file is missing.\n" );
            usage();
        }
        filename = *argv;
    }
    
    /* --- now load the input file --- */
    ptsData *pts = loadPtsFile(filename, 4);
    printf("Input file '%s' loaded\n", filename);
    savePtsCrgFile(pts, outfilename);
     
    freePts(pts);
    printf( "main: normal termination\n" );
    
    return 1;
}

